name: 'Semver Parse'
description: 'Parses a semantic version from a given string or git tag'

inputs:
  source:
    description: 'A source to take string from'
    required: false
  string:
    description: 'A string to extract semver from'
    required: false
  fallback:
    description: 'A string to use as a tag when it is not found'
    required: false
  pattern:
    description: 'Regex to extract semantic version from a input string'
    required: false

outputs:
  full:
    description: 'A full representation of the semver'
  major:
    description: 'MAJOR part of the semver'
  minor:
    description: 'MINOR part of the semver'
  patch:
    description: 'PATCH part of the semver'
  prerelease:
    description: 'PRERELEASE part of the semver'
  build:
    description: 'BUILD part of the semver'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'play'
  color: 'gray-dark'
